api_login_check:
  path: /booking/api/login

booking_admin:
  path: /booking/admin
  controller: Comsa\BookingBundle\Controller\AdminController:index

booking:
  path: /booking
  controller: Comsa\BookingBundle\Controller\FrontController:index

admin:
  type: annotation
  resource: Comsa\BookingBundle\Controller\AdminController
  prefix: /booking/api

booking_front:
  type: annotation
  resource: Comsa\BookingBundle\Controller\BookingController
  prefix: /booking/api
